# Generated by Django 3.1.5 on 2021-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='uploads/books/default.jpg', upload_to='uploads/books/'),
        ),
    ]
