# Generated by Django 3.1.5 on 2021-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='libraryapp/static/uploads/books/default.jpg', upload_to='libraryapp/static/uploads/books/'),
        ),
    ]
