# Generated by Django 3.1.5 on 2021-01-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_auto_20210129_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirement',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.reader'),
        ),
    ]
