# Generated by Django 3.1.5 on 2021-02-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='subject',
        ),
    ]
