# Generated by Django 3.1.5 on 2021-02-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_auto_20210201_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sebject',
            new_name='subject',
        ),
    ]
